import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import AppModal from "@/components/AppModal.vue";
import CKEditor from "@ckeditor/ckeditor5-vue";
import Paginate from "vuejs-paginate-next";
const app = createApp(App);
app.use(store);
app.use(router);
app.mount("#app");
app.component("app-modal", AppModal);
app.use(CKEditor);
app.component("app-paginate", Paginate);
